# segyviewer-
(base) C:\>pip install segyviewer Collecting segyviewer   Using cached https://files.pythonhosted.org/packages/64/71/e3f9e7e97a2d6a14dd1942c60b4ec0407f6fff022ef3c5afb3b4bddff144/segyviewer-1.1.3.tar.gz     Complete output from command python setup.py egg_info:     Download error on https://pypi.org/simple/setuptools_scm/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!     Download error on https://pypi.org/simple/setuptools-scm/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!     Couldn't find index page for 'setuptools_scm' (maybe misspelled?)     Download error on https://pypi.org/simple/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!     No local packages or working download links found for setuptools_scm     Traceback (most recent call last):       File "&lt;string>", line 1, in &lt;module>       File "C:\Users\ASHUTO~1.GAR\AppData\Local\Temp\pip-install-ak7og3fh\segyviewer\setup.py", line 36, in &lt;module>         'Topic :: Utilities'       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup         _install_setup_requires(attrs)       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires         dist.fetch_build_eggs(dist.setup_requires)       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\dist.py", line 724, in fetch_build_eggs         replace_conflicting=True,       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve         replace_conflicting=replace_conflicting       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match         return self.obtain(req, installer)       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain         return installer(requirement)       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\dist.py", line 791, in fetch_build_egg         return cmd.easy_install(req)       File "C:\Users\Ashutosh.Garg\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install         raise DistutilsError(msg)     distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')      ---------------------------------------- Command "python setup.py egg_info" failed with error code 1 in C:\Users\ASHUTO~1.GAR\AppData\Local\Temp\pip-install-ak7og3fh\segyviewer\
